project:
  type: website

website:
  title: "Meta-analysis Overall Accuracy in Remote Sensing"
  sidebar:
    contents: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: analysis.qmd
        text: Redo the analysis

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

